# Generated by Django 3.0 on 2021-05-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title', 'published')},
        ),
    ]
