# Generated by Django 3.0 on 2021-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210522_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(max_length=10),
        ),
    ]
