# Generated by Django 3.0 on 2021-05-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210522_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_id',
        ),
    ]
